export const PA = "p",
  H1 = "h1",
  H2 = "h2",
  H3 = "h3",
  DIV = "div",
  TABLE = "table",
  TABLA = "tabla",
  TH = "th",
  TR = "tr",
  TD = "td",
  SECT = "section",
  ART = "article",
  OP = "option"
export const TITULO = "titulo",
  TIPO = "tipo";
export const STYLE = "style",
  BG_COLOR = "background-color: ";
export const IDSELECT = "clases",
  IDMAIN = "contenido";
export let p, p1, h1, h2, h3, div, tablo, th, tr, td;