INSERT INTO USER_SIGUE_PARTIDO (IDU_Usuarios, IDP_Partidos)
    VALUE(1, 1);
INSERT INTO USER_SIGUE_PARTIDO (IDU_Usuarios, IDP_Partidos)
    VALUE(1, 3);

INSERT INTO USER_SIGUE_PARTIDO (IDU_Usuarios, IDP_Partidos)
    VALUE(2, 2);
INSERT INTO USER_SIGUE_PARTIDO (IDU_Usuarios, IDP_Partidos)
    VALUE(2, 4);