INSERT INTO USER_SIGUE_JUGADOR (IDU_Usuarios, IDJ_Jugadores)
    VALUE(1,1);
INSERT INTO USER_SIGUE_JUGADOR (IDU_Usuarios, IDJ_Jugadores)
    VALUE(1,2);
INSERT INTO USER_SIGUE_JUGADOR (IDU_Usuarios, IDJ_Jugadores)
    VALUE(1,3);

INSERT INTO USER_SIGUE_JUGADOR (IDU_Usuarios, IDJ_Jugadores)
    VALUE(2,40);
INSERT INTO USER_SIGUE_JUGADOR (IDU_Usuarios, IDJ_Jugadores)
    VALUE(2,35);
INSERT INTO USER_SIGUE_JUGADOR (IDU_Usuarios, IDJ_Jugadores)
    VALUE(2,26);